server:
  port: 7585
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carDB?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9595/oauth/check_token
    client:
      client-id: oriental
      client-secret: oriental
